language: csharp
solution: Autopsy.sln
dotnet: 3.1.101
script:
  - dotnet clean
  - dotnet restore
  - dotnet build
  - dotnet test
deploy:
  provider: script
  skip_cleanup: true
  on:
    tags: true
    branch: master
  script: bash deploy.sh